file_IO.h
file_mode
typedef FILE file_t
File Handling Abstractions.
file_IO.h @Kevin-Caldwell Abstracted Functions for File IO. Implementation in file_IO.c should be adapted to fit the respective file system. The datatype used throughout the code is file_t.
typedef enum file_mode FileMode
const char* file_modes_str[][]
Referenced by F_OPEN.
file_t * F_OPEN(const char *file_name, FileMode open_mode)
References file_modes_str, Log_add.
Referenced by Decoder_DecodeBody, EncodeBody, InitializeVarIntStream, LoadConstantFile, Log_init, ReadImageFromCSV, RunPredictor, SaveArrayAsCSV, SaveImageAsCSV, TestReconstructor, UHI_Initialize, VUF_initialize.
size_t F_WRITE(const void *write_ptr, size_t member_size, size_t member_count, file_t *file_ptr)
Referenced by Predict, ReconstructPixel, StreamVarInteger, VUF_append.
size_t F_READ(void *destination, size_t size, size_t arr_length, file_t *file_stream)
Referenced by ReadImageFromCSV, UHI_ReadPixel, VUF_initialize, VUF_read_stack.
int F_CLOSE(file_t *stream)
Referenced by CloseVarIntegerStream, LoadConstantFile, Log_close, RunPredictor, SaveArrayAsCSV, SaveImageAsCSV, test_UHI, TestReconstructor, UHI_close, VUF_close.
int F_EMPTY(file_t *stream)
int F_SEEK(file_t *stream, long int offset)
References offset.
Referenced by UHI_ReadPixel.