synthetic_image_generator.c
WRI
int WithinRect2(dim2 point, dim2 top_left, dim2 bottom_right)
References INSIDE_INTERVAL, dim2::x, dim2::y.
int WithinRect3(dim3 point, dim3 top_left, dim3 bottom_right)
References INSIDE_INTERVAL, dim3::x, dim3::y, dim3::z.
int SpreadPoint2(dim2 **points, dim2 bounds, UINT point_count)
References INIT_ARRAY, dim2::x, dim2::y.
Referenced by GenerateVoronoiFlat2D.
int SpreadPoint3(dim3 **points, dim3 bounds, UINT point_count)
References INIT_ARRAY, dim3::x, dim3::y, dim3::z.
Referenced by GenerateVoronoiFlat3DLocal, GenerateVoronoiFlat3DNaive.
int GenerateVoronoiFlat2D(image2 *result, UINT point_count)
References image2::data, Manhattan2, image2::size, SpreadPoint2, dim2::x, dim2::y.
UINT GetMinDistance3Naive(dim3 point, dim3 *points, UINT point_count)
References Manhattan3.
Referenced by GenerateVoronoiFlat3DNaive.
int GenerateVoronoiFlat3DNaive(image3 *result, UINT point_count)
References GetMinDistance3Naive, SetPixel, image::size, SpreadPoint3, dim3::x, dim3::y, dim3::z.
Referenced by test_UHI.
int GeneratePointLocales(dim3 *points, UINT **p_locales, UINT **p_true_indices, UINT point_count)
References INIT_ARRAY, Manhattan3.
Referenced by GenerateVoronoiFlat3DLocal.
UINT GetMinDistance3Locales(dim3 point, dim3 *points, UINT *locales, UINT *color_indices, UINT point_count)
References Manhattan3.
Referenced by GenerateVoronoiFlat3DLocal, ShadeVoronoiBox3.
int ShadeVoronoiBox3(image3 *img, dim3 top_right, dim3 bounds, dim3 *points, UINT *locales, UINT *color_indices, UINT point_count)
References GetMinDistance3Locales, SetPixel, ShadeVoronoiBox3, dim3::x, dim3::y, dim3::z.
Referenced by ShadeVoronoiBox3.
int GenerateVoronoiFlat3DLocal(image3 *result, UINT point_count)
Faster Method for Generating Voronoi Diagrams.
result point_count
References GeneratePointLocales, GetMinDistance3Locales, SetPixel, image::size, SpreadPoint3, dim3::x, dim3::y, dim3::z.
Referenced by GenerateVoronoiImage.