encoder_helper_functions.h
void PrintBinary(uint8_t byte)
encoder_helper_functions.h @Kevin-Caldwell Global Functions for Encoding the image Features Print a byte in Binary Encode n bit data into m bit buffer, n < 8, data < 8 Dependencies inttypes.h stdio.h
Referenced by Encode, PrepareImageMetadata.
void Encode(uint8_t *destination, uint8_t index, uint8_t data, uint8_t length)
References PrintBinary.
Referenced by PrepareImageMetadata, PreparePredictorMetadata, PrepareSampleAdaptiveEntropyCoder.