reconstructor.h
Ps
reconstructor.h @Kevin-Caldwell Major Function Definitions of Reconstructor Module Features Reconstructing an Image Reconstructing Individual Pixels Reconstructor Testing Uses Validation of Predictor Output Validation of Complete Compression Output Dependencies constants.h math_functions.h linear_algebra.h image.h quantizer.h csv-io.h predictor.h inttypes.h TODO Internal Dependencies TODO Finish Reconstructor Module Test Reconstruct Pixel Reconstructor Test Reconstructor Validate Reconstructor with Python
typedef uint32_t weight_t
int C
void ReconstructPixel(image *hIMG, image *result, INDEX z, INDEX y, INDEX x, FILE *file_ptr)
References C, ClippedQuantizerBinCenter, DoubleResolutionPredictedSample, DoubleResolutionPredictionError, F_WRITE, FindLocalSum, GetPixel, global_cache, HighResolutionPredictedSample, InitializeWeights, PredictedCentralLocalDifference, PredictedSample, QuantizerIndexUnmapper, SetPixel, UpdateWeights, PredictorCache::weights.
Referenced by Reconstructor.
void Reconstructor(image *predicted_values, image *reconstructed, FILE *file_ptr)
References C, InitalizeImageConstants, InitalizePredictorConstants, LoadConstantFile, NULL, Nz, PREDICTION_MODE, predictor_constants, PREDICTOR_CONSTANTS_LOCATION, Ps, ReconstructPixel, image::size, dim3::x, dim3::y, dim3::z.
Referenced by TestReconstructor.
void TestReconstructor(char *file_name)
References image::data, F_CLOSE, F_OPEN, global_cache, Image_Equals, InitializePredictorCache, InitImage, ReadImageFromCSV, Reconstructor, RunPredictor, sample, image::size, WRITE, dim3::x, dim3::y, dim3::z.
Referenced by main.