logs.h
void Log_init()
References _GET_PRINT_TIME, APPEND, F_OPEN, log_file, log_fptr.
Referenced by main.
void Log_close()
References F_CLOSE, Log_add, log_fptr.
Referenced by main.
void Log_add(const char *text)
References _GET_PRINT_TIME, log_fptr.
Referenced by F_OPEN, Log_close, main, PredictImage, RunPredictor, testVUF_Write.
void Log_error(char *text)
References _GET_PRINT_TIME, log_fptr.
Referenced by PredictImage, ReadImageFromCSV, RunPredictor, SaveArrayAsCSV, SaveImageAsCSV, VUF_initialize.