logs.c
char log_file[][]
Referenced by Log_init.
char _time_str[100][100]
Referenced by _GET_PRINT_TIME.
file_t* log_fptr
Referenced by Log_add, Log_close, Log_error, Log_init.
char * _GET_PRINT_TIME()
References _time_str, NULL.
Referenced by Log_add, Log_error, Log_init.
void Log_init()
References _GET_PRINT_TIME, APPEND, F_OPEN, log_file, log_fptr.
Referenced by main.
void Log_close()
References F_CLOSE, Log_add, log_fptr.
Referenced by main.
void Log_add(const char *text)
References _GET_PRINT_TIME, log_fptr.
Referenced by F_OPEN, Log_close, main, PredictImage, RunPredictor, testVUF_Write.
void Log_error(char *text)
References _GET_PRINT_TIME, log_fptr.
Referenced by PredictImage, ReadImageFromCSV, RunPredictor, SaveArrayAsCSV, SaveImageAsCSV, VUF_initialize.