uhi_io.c
int UHI_Initialize(UHI *stream, dim3 buffer_size, const char *file_name, FileMode file_mode)
References UncompressedHyperspectralImage::cache, F_OPEN, UncompressedHyperspectralImage::fs, READ.
Referenced by test_UHI.
int UHI_WriteImage(const char *filename, const image *source)
PIXEL UHI_ReadPixel(UHI *stream, dim3 index)
References UncompressedHyperspectralImage::cache, F_READ, F_SEEK, UncompressedHyperspectralImage::fs, UncompressedHyperspectralImage::size, dim3::x, dim3::y, dim3::z.
Referenced by Proxy_GetPixel, test_UHI.
int UHI_WritePixel(const UHI *stream, dim3 index, PIXEL value)
Referenced by Proxy_SetPixel, test_UHI.
int UHI_close(UHI *stream)
References F_CLOSE, UncompressedHyperspectralImage::fs.
PIXEL Proxy_GetPixel(uIMG *hIMG, INDEX x, INDEX y, INDEX z)
References UHI_ReadPixel.
void Proxy_SetPixel(uIMG *hIMG, INDEX x, INDEX y, INDEX z, PIXEL value)
References UHI_WritePixel.