math_functions.h
NULL
math_functions.h @Kevin-Caldwell Mathematical Helper Functions for use throughout code.
CLIP
INSIDE_INTERVAL
OUTSIDE_INTERVAL
SIGN
SIGN_P
MOD
MAX
MIN
BPOW
SQ
RetVal
typedef size_t DIM
typedef unsigned int UINT
typedef uint16_t PIXEL
typedef uint16_t INDEX
typedef struct dim3 dim3
3D Dimension Struct, used to describe size and 3D-Indicies. Spatial Dimensions: x, y Spectral Band: z
typedef struct dim2 dim2
UINT Euclidian2(dim2 pt1, dim2 pt2)
References SQ, dim2::x, dim2::y.
UINT Euclidian3(dim3 pt1, dim3 pt2)
References SQ, dim3::x, dim3::y, dim3::z.
UINT Manhattan2(dim2 pt1, dim2 pt2)
References dim2::x, dim2::y.
Referenced by GenerateVoronoiFlat2D.
UINT Manhattan3(dim3 pt1, dim3 pt2)
References dim3::x, dim3::y, dim3::z.
Referenced by GeneratePointLocales, GetMinDistance3Locales, GetMinDistance3Naive.