cache_predictor.h
typedef struct PredictorCache PredictorCache
char* CacheFiles[][]
PredictorCache* global_cache
Referenced by Predict, PredictedCentralLocalDifference, PredictImage, ReconstructPixel, TestReconstructor.
int InitializePredictorCache(PredictorCache **p_cache, image *hIMG)
References PredictorCache::cache_space, InitializeWeights, InitImage, image::size, PredictorCache::weights, dim3::x, dim3::y, dim3::z.
Referenced by PredictImage, TestReconstructor.
int DeletePredictorCache(PredictorCache *p_cache)
References PredictorCache::cache_space.
Referenced by PredictImage.