.TH "main Directory Reference" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcompressor\&.c\fP"
.br
.ti -1c
.RI "file \fBdecompressor\&.c\fP"
.br
.ti -1c
.RI "file \fBimage_handler\&.c\fP"
.br
.in -1c
