.TH "include/encoder Directory Reference" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/encoder Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbody\&.h\fP"
.br
.ti -1c
.RI "file \fBencoder\&.h\fP"
.br
.ti -1c
.RI "file \fBencoder_helper_functions\&.h\fP"
.br
.ti -1c
.RI "file \fBheader\&.h\fP"
.br
.ti -1c
.RI "file \fBstream_encoder\&.h\fP"
.br
.in -1c
