.TH "include/math Directory Reference" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/math Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlinear_algebra\&.h\fP"
.br
.ti -1c
.RI "file \fBmath_functions\&.h\fP"
.br
.in -1c
