.TH "include/predictor Directory Reference" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/predictor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlocal_differences\&.h\fP"
.br
.ti -1c
.RI "file \fBlocal_sum\&.h\fP"
.br
.ti -1c
.RI "file \fBpredictor\&.h\fP"
.br
.ti -1c
.RI "file \fBquantizer\&.h\fP"
.br
.ti -1c
.RI "file \fBsample_representative\&.h\fP"
.br
.ti -1c
.RI "file \fBweights\&.h\fP"
.br
.in -1c
