.TH "src/cache_predictor.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cache_predictor.c
.SH SYNOPSIS
.br
.PP
\fC#include 'cache/cache_predictor\&.h'\fP
.br
\fC#include 'predictor/local_sum\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBInitializePredictorCache\fP (\fBPredictorCache\fP **ptr_p_cache, \fBimage\fP *hIMG)"
.br
.ti -1c
.RI "int \fBDeletePredictorCache\fP (\fBPredictorCache\fP *p_cache)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPredictorCache\fP * \fBglobal_cache\fP = \fBNULL\fP"
.br
.ti -1c
.RI "char * \fBCacheFiles\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int DeletePredictorCache (\fBPredictorCache\fP * p_cache)"

.PP
Definition at line \fB43\fP of file \fBcache_predictor\&.c\fP\&.
.SS "int InitializePredictorCache (\fBPredictorCache\fP ** ptr_p_cache, \fBimage\fP * hIMG)"

.PP
Definition at line \fB16\fP of file \fBcache_predictor\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char* CacheFiles[]"
\fBInitial value:\fP.PP
.nf
= {"raw\&.csv",
                      "local\-sums\&.csv",
                      "sample\-representatives\&.csv",
                      "predicted_sample\&.csv",
                      "central_local_difference\&.csv",
                      "predicted_central_local_difference\&.csv",
                      "clipped_quanitzer_bin_center\&.csv", "quantizer_index\&.csv"}
.fi

.PP
Definition at line \fB6\fP of file \fBcache_predictor\&.c\fP\&.
.SS "\fBPredictorCache\fP* global_cache = \fBNULL\fP"

.PP
Definition at line \fB5\fP of file \fBcache_predictor\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
