.TH "build/CMakeFiles/3.22.1/CompilerIdC/CMakeCCompilerId.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/CMakeFiles/3.22.1/CompilerIdC/CMakeCCompilerId.c
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__has_include\fP(x)   0"
.br
.ti -1c
.RI "#define \fBCOMPILER_ID\fP   ''"
.br
.ti -1c
.RI "#define \fBSTRINGIFY_HELPER\fP(X)   #X"
.br
.ti -1c
.RI "#define \fBSTRINGIFY\fP(X)   \fBSTRINGIFY_HELPER\fP(X)"
.br
.ti -1c
.RI "#define \fBPLATFORM_ID\fP"
.br
.ti -1c
.RI "#define \fBARCHITECTURE_ID\fP"
.br
.ti -1c
.RI "#define \fBDEC\fP(n)"
.br
.ti -1c
.RI "#define \fBHEX\fP(n)"
.br
.ti -1c
.RI "#define \fBC_VERSION\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char const  * \fBinfo_compiler\fP = 'INFO' ':' 'compiler[' COMPILER_ID ']'"
.br
.ti -1c
.RI "char const  * \fBinfo_platform\fP = 'INFO' ':' 'platform[' PLATFORM_ID ']'"
.br
.ti -1c
.RI "char const  * \fBinfo_arch\fP = 'INFO' ':' 'arch[' ARCHITECTURE_ID ']'"
.br
.ti -1c
.RI "const char * \fBinfo_language_standard_default\fP"
.br
.ti -1c
.RI "const char * \fBinfo_language_extensions_default\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __has_include(x)   0"

.PP
Definition at line \fB17\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define ARCHITECTURE_ID"

.PP
Definition at line \fB652\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define C_VERSION"

.PP
Definition at line \fB741\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define COMPILER_ID   ''"

.PP
Definition at line \fB396\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define DEC(n)"
\fBValue:\fP.PP
.nf
  ('0' + (((n) / 10000000)%10)), \\
  ('0' + (((n) / 1000000)%10)),  \\
  ('0' + (((n) / 100000)%10)),   \\
  ('0' + (((n) / 10000)%10)),    \\
  ('0' + (((n) / 1000)%10)),     \\
  ('0' + (((n) / 100)%10)),      \\
  ('0' + (((n) / 10)%10)),       \\
  ('0' +  ((n) % 10))
.fi

.PP
Definition at line \fB656\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define HEX(n)"
\fBValue:\fP.PP
.nf
  ('0' + ((n)>>28 & 0xF)), \\
  ('0' + ((n)>>24 & 0xF)), \\
  ('0' + ((n)>>20 & 0xF)), \\
  ('0' + ((n)>>16 & 0xF)), \\
  ('0' + ((n)>>12 & 0xF)), \\
  ('0' + ((n)>>8  & 0xF)), \\
  ('0' + ((n)>>4  & 0xF)), \\
  ('0' + ((n)     & 0xF))
.fi

.PP
Definition at line \fB667\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define PLATFORM_ID"

.PP
Definition at line \fB524\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define STRINGIFY(X)   \fBSTRINGIFY_HELPER\fP(X)"

.PP
Definition at line \fB417\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define STRINGIFY_HELPER(X)   #X"

.PP
Definition at line \fB416\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB776\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char const* info_arch = 'INFO' ':' 'arch[' ARCHITECTURE_ID ']'"

.PP
Definition at line \fB733\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "char const* info_compiler = 'INFO' ':' 'compiler[' COMPILER_ID ']'"

.PP
Definition at line \fB403\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "const char* info_language_extensions_default"
\fBInitial value:\fP.PP
.nf
= "INFO" ":" "extensions_default["






  "OFF"

"]"
.fi

.PP
Definition at line \fB757\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "const char* info_language_standard_default"
\fBInitial value:\fP.PP
.nf
=
  "INFO" ":" "standard_default[" C_VERSION "]"
.fi

.PP
Definition at line \fB754\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SS "char const* info_platform = 'INFO' ':' 'platform[' PLATFORM_ID ']'"

.PP
Definition at line \fB732\fP of file \fBCMakeCCompilerId\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
