.TH "csv_io" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csv_io
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBReadCSV\fP (filename)"
.br
.ti -1c
.RI "\fBSaveCSV\fP (np_array_3d, output_path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ReadCSV ( filename)"

.PP
Definition at line \fB3\fP of file \fBcsv_io\&.py\fP\&.
.SS "SaveCSV ( np_array_3d,  output_path)"

.PP
Definition at line \fB39\fP of file \fBcsv_io\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
