.TH "main/decompressor.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main/decompressor.c
.SH SYNOPSIS
.br
.PP
\fC#include 'decompressor/reconstructor\&.h'\fP
.br
\fC#include 'decompressor/decoder\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argInt, char **argS)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBDEBUG\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argInt, char ** argS)"

.PP
Definition at line \fB8\fP of file \fBdecompressor\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char DEBUG = 0"

.PP
Definition at line \fB6\fP of file \fBdecompressor\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
