.TH "deprecated" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP

.IP "\fBFile \fBcache_predictor\&.h\fP \fP" 1c
Large Memory Usage, ineffective for debug\&.  
.IP "\fBGlobal \fBL_SHIFT\fP (x, s)\fP" 1c
Replaced by \fBvarIntFile_IO\&.h\fP  
.IP "\fBStruct \fBPredictorCache\fP \fP" 1c
 The Predictor testing has been re-implemented to accomodate more streamlined and memory-efficient debugging processes\&.
.PP

