.TH "dim2" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dim2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math_functions\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDIM\fP \fBx\fP"
.br
.ti -1c
.RI "\fBDIM\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB64\fP of file \fBmath_functions\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBDIM\fP x"

.PP
Definition at line \fB65\fP of file \fBmath_functions\&.h\fP\&.
.SS "\fBDIM\fP y"

.PP
Definition at line \fB66\fP of file \fBmath_functions\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
