.TH "dim3" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dim3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math_functions\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDIM\fP \fBx\fP"
.br
.ti -1c
.RI "\fBDIM\fP \fBy\fP"
.br
.ti -1c
.RI "\fBDIM\fP \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
3D Dimension Struct, used to describe size and 3D-Indicies\&.
.PP
Spatial Dimensions: x, y Spectral Band: z 
.PP
Definition at line \fB58\fP of file \fBmath_functions\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBDIM\fP x"

.PP
Definition at line \fB59\fP of file \fBmath_functions\&.h\fP\&.
.SS "\fBDIM\fP y"

.PP
Definition at line \fB60\fP of file \fBmath_functions\&.h\fP\&.
.SS "\fBDIM\fP z"

.PP
Definition at line \fB61\fP of file \fBmath_functions\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
