.TH "display_debugging" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_debugging
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdisplay_images\fP (i)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBCacheFiles\fP"
.br
.ti -1c
.RI "\fBnum_images\fP = len(\fBCacheFiles\fP)"
.br
.ti -1c
.RI "int \fBrows\fP = 2 if \fBnum_images\fP > 5 else 1"
.br
.ti -1c
.RI "tuple \fBcols\fP = (\fBnum_images\fP + 1) // 2"
.br
.ti -1c
.RI "\fBfig\fP"
.br
.ti -1c
.RI "\fBaxes\fP"
.br
.ti -1c
.RI "\fBfigsize\fP"
.br
.ti -1c
.RI "list \fBimages\fP = []"
.br
.ti -1c
.RI "\fBanim\fP = FuncAnimation(\fBfig\fP, \fBdisplay_images\fP, frames = 100, interval=1000)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "display_images ( i)"

.PP
Definition at line \fB17\fP of file \fBdisplay_debugging\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "anim = FuncAnimation(\fBfig\fP, \fBdisplay_images\fP, frames = 100, interval=1000)"

.PP
Definition at line \fB41\fP of file \fBdisplay_debugging\&.py\fP\&.
.SS "axes"

.PP
Definition at line \fB11\fP of file \fBdisplay_debugging\&.py\fP\&.
.SS "list CacheFiles"
\fBInitial value:\fP.PP
.nf
1 =  ["raw",
2    "predictor", "local\-sums"]
.fi

.PP
Definition at line \fB4\fP of file \fBdisplay_debugging\&.py\fP\&.
.SS "cols = (\fBnum_images\fP + 1) // 2"

.PP
Definition at line \fB9\fP of file \fBdisplay_debugging\&.py\fP\&.
.SS "fig"

.PP
Definition at line \fB11\fP of file \fBdisplay_debugging\&.py\fP\&.
.SS "figsize"

.PP
Definition at line \fB11\fP of file \fBdisplay_debugging\&.py\fP\&.
.SS "list images = []"

.PP
Definition at line \fB15\fP of file \fBdisplay_debugging\&.py\fP\&.
.SS "num_images = len(\fBCacheFiles\fP)"

.PP
Definition at line \fB7\fP of file \fBdisplay_debugging\&.py\fP\&.
.SS "rows = 2 if \fBnum_images\fP > 5 else 1"

.PP
Definition at line \fB8\fP of file \fBdisplay_debugging\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
