.TH "include/constants/encoder_constants.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/constants/encoder_constants.h
.SH SYNOPSIS
.br
.PP
\fC#include 'math/math_functions\&.h'\fP
.br
\fC#include 'constants/constants\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOUTPUT_WORD_SIZE\fP   8"
.br
.ti -1c
.RI "#define \fBENTROPY_CODER\fP   0b00"
.br
.ti -1c
.RI "#define \fBQUANTIZER_FIDELITY_CONTROL\fP   0b00"
.br
.ti -1c
.RI "#define \fBTABLE_COUNT\fP   0"
.br
.ti -1c
.RI "#define \fBSIZEOF_HEADER_ESSENTIAL\fP   12"
.br
.ti -1c
.RI "#define \fBSAMPLE_REP_FLAG\fP   1"
.br
.ti -1c
.RI "#define \fBWEO_TABLE_FLAG\fP   0"
.br
.ti -1c
.RI "#define \fBWEIGHT_INITIALIZATION_TABLE_FLAG\fP   0"
.br
.ti -1c
.RI "#define \fBBAND_VARYING_DAMPING_FLAG\fP   0"
.br
.ti -1c
.RI "#define \fBDAMPING_TABLE_FLAG\fP   0"
.br
.ti -1c
.RI "#define \fBBAND_VARYING_OFFSET_FLAG\fP   0"
.br
.ti -1c
.RI "#define \fBOFFSET_TABLE_FLAG\fP   0"
.br
.ti -1c
.RI "#define \fBFIXED_DAMPING\fP   0"
.br
.ti -1c
.RI "#define \fBFIXED_OFFSET\fP   0"
.br
.ti -1c
.RI "#define \fBRESCALING_COUNTER_SIZE\fP   1"
.br
.ti -1c
.RI "#define \fBINITIAL_COUNT_EXPONENT\fP   1"
.br
.ti -1c
.RI "#define \fBACCUMULATOR_INITIALIZATION\fP   0b1111"
.br
.ti -1c
.RI "#define \fBACCUMULATOR_INITIALIZATION_TABLE_FLAG\fP   0"
.br
.ti -1c
.RI "#define \fBINITIAL_COUNT_EXPONENT\fP   1"
.br
.ti -1c
.RI "#define \fBACCUMULATOR_INITIALIZATION_CONSTANT\fP   14"
.br
.ti -1c
.RI "#define \fBUNARY_LENGTH_LIMIT\fP   8"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBB\fP"
.br
.ti -1c
.RI "unsigned int \fBU_max\fP"
.br
.ti -1c
.RI "int \fBK\fP"
.br
.ti -1c
.RI "int \fBGamma1\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ACCUMULATOR_INITIALIZATION   0b1111"

.PP
Definition at line \fB75\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define ACCUMULATOR_INITIALIZATION_CONSTANT   14"

.PP
Definition at line \fB84\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define ACCUMULATOR_INITIALIZATION_TABLE_FLAG   0"

.PP
Definition at line \fB76\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define BAND_VARYING_DAMPING_FLAG   0"

.PP
Definition at line \fB53\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define BAND_VARYING_OFFSET_FLAG   0"

.PP
Definition at line \fB61\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define DAMPING_TABLE_FLAG   0"

.PP
Definition at line \fB57\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define ENTROPY_CODER   0b00"

.PP
Definition at line \fB32\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define FIXED_DAMPING   0"

.PP
Definition at line \fB67\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define FIXED_OFFSET   0"

.PP
Definition at line \fB68\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define INITIAL_COUNT_EXPONENT   1"

.PP
Definition at line \fB74\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define INITIAL_COUNT_EXPONENT   1"

.PP
Definition at line \fB74\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define OFFSET_TABLE_FLAG   0"

.PP
Definition at line \fB65\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define OUTPUT_WORD_SIZE   8"
\fBencoder_constants\&.h\fP 
.PP
\fBAuthor\fP
.RS 4
@Kevin-Caldwell
.RE
.PP
Contains all Encoder-Specific Constants
.PP
Uses Encoder Abstraction
.PP
Dependencies \fBmath_functions\&.h\fP \fBconstants\&.h\fP
.PP
TODO Determine Encoder-Specific Constants Add Effects of Constants in Comments 
.PP
Definition at line \fB26\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define QUANTIZER_FIDELITY_CONTROL   0b00"

.PP
Definition at line \fB39\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define RESCALING_COUNTER_SIZE   1"

.PP
Definition at line \fB73\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define SAMPLE_REP_FLAG   1"

.PP
Definition at line \fB45\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define SIZEOF_HEADER_ESSENTIAL   12"

.PP
Definition at line \fB43\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define TABLE_COUNT   0"

.PP
Definition at line \fB41\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define UNARY_LENGTH_LIMIT   8"

.PP
Definition at line \fB85\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define WEIGHT_INITIALIZATION_TABLE_FLAG   0"

.PP
Definition at line \fB47\fP of file \fBencoder_constants\&.h\fP\&.
.SS "#define WEO_TABLE_FLAG   0"

.PP
Definition at line \fB46\fP of file \fBencoder_constants\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const int B\fC [extern]\fP"

.PP
Definition at line \fB3\fP of file \fBencoder_constants\&.c\fP\&.
.SS "int Gamma1\fC [extern]\fP"

.PP
Definition at line \fB7\fP of file \fBencoder_body\&.c\fP\&.
.SS "int K\fC [extern]\fP"

.PP
Definition at line \fB5\fP of file \fBencoder_body\&.c\fP\&.
.SS "unsigned int U_max\fC [extern]\fP"

.PP
Definition at line \fB6\fP of file \fBencoder_body\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
