.TH "src/encoder_constants.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/encoder_constants.c
.SH SYNOPSIS
.br
.PP
\fC#include 'constants/encoder_constants\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBB\fP = \fBCLIP\fP(\fBOUTPUT_WORD_SIZE\fP, 1, 8)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int B = \fBCLIP\fP(\fBOUTPUT_WORD_SIZE\fP, 1, 8)"

.PP
Definition at line \fB3\fP of file \fBencoder_constants\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
