.TH "src/encoder_helper.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/encoder_helper.c
.SH SYNOPSIS
.br
.PP
\fC#include 'encoder/encoder_helper_functions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPrintBinary\fP (uint8_t byte)"
.br
.ti -1c
.RI "void \fBEncode\fP (uint8_t *destination, uint8_t index, uint8_t data, uint8_t length)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Encode (uint8_t * destination, uint8_t index, uint8_t data, uint8_t length)"

.PP
Definition at line \fB12\fP of file \fBencoder_helper\&.c\fP\&.
.SS "void PrintBinary (uint8_t byte)"
\fBencoder_helper_functions\&.h\fP 
.PP
\fBAuthor\fP
.RS 4
@Kevin-Caldwell
.RE
.PP
Global Functions for Encoding the image
.PP
Features Print a byte in Binary Encode n bit data into m bit buffer, n < 8, data < 8
.PP
Dependencies inttypes\&.h stdio\&.h 
.PP
Definition at line \fB3\fP of file \fBencoder_helper\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
