.TH "file_compare" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_compare
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCompareResults\fP (c_pred_file, python_pred_file)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBn\fP = len(sys\&.argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "CompareResults ( c_pred_file,  python_pred_file)"

.PP
Definition at line \fB5\fP of file \fBfile_compare\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "n = len(sys\&.argv)"

.PP
Definition at line \fB19\fP of file \fBfile_compare\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
