.TH "python/file_compare.py" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/file_compare.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBfile_compare\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCompareResults\fP (c_pred_file, python_pred_file)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBn\fP = len(sys\&.argv)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
