.TH "fVector3" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fVector3
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
3D floating point vector 
.PP
Definition at line \fB11\fP of file \fBperlin_noise\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "float x"

.PP
Definition at line \fB13\fP of file \fBperlin_noise\&.c\fP\&.
.SS "float y"

.PP
Definition at line \fB13\fP of file \fBperlin_noise\&.c\fP\&.
.SS "float z"

.PP
Definition at line \fB13\fP of file \fBperlin_noise\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
