.TH "python/generate_perlin_image.py" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/generate_perlin_image.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgenerate_perlin_image\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBp\fP = perlin\&.perlin(1000)"
.br
.ti -1c
.RI "\fBimg\fP = p\&.three(100, 100, 100)"
.br
.ti -1c
.RI "\fBframe\fP = np\&.zeros(shape=(640, 512))"
.br
.ti -1c
.RI "\fBstart\fP = time\&.clock_gettime_ns(0)"
.br
.ti -1c
.RI "\fBend\fP = time\&.clock_gettime_ns(0)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
