.TH "generate_perlin_image" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generate_perlin_image
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBp\fP = perlin\&.perlin(1000)"
.br
.ti -1c
.RI "\fBimg\fP = p\&.three(100, 100, 100)"
.br
.ti -1c
.RI "\fBframe\fP = np\&.zeros(shape=(640, 512))"
.br
.ti -1c
.RI "\fBstart\fP = time\&.clock_gettime_ns(0)"
.br
.ti -1c
.RI "\fBend\fP = time\&.clock_gettime_ns(0)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "end = time\&.clock_gettime_ns(0)"

.PP
Definition at line \fB14\fP of file \fBgenerate_perlin_image\&.py\fP\&.
.SS "frame = np\&.zeros(shape=(640, 512))"

.PP
Definition at line \fB9\fP of file \fBgenerate_perlin_image\&.py\fP\&.
.SS "img = p\&.three(100, 100, 100)"

.PP
Definition at line \fB8\fP of file \fBgenerate_perlin_image\&.py\fP\&.
.SS "p = perlin\&.perlin(1000)"

.PP
Definition at line \fB7\fP of file \fBgenerate_perlin_image\&.py\fP\&.
.SS "start = time\&.clock_gettime_ns(0)"

.PP
Definition at line \fB10\fP of file \fBgenerate_perlin_image\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
