.TH "GolombInt" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GolombInt
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <body\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBdata\fP"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Package Struct for storing Compressed Data\&.
.PP
data: 32 bit int storing varInt Data length: bit length of the value stored in data 
.PP
Definition at line \fB44\fP of file \fBbody\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t data"

.PP
Definition at line \fB45\fP of file \fBbody\&.h\fP\&.
.SS "uint32_t length"

.PP
Definition at line \fB46\fP of file \fBbody\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
