.TH "HashTable" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash_table\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBkeys\fP [\fBHASH_CAPACITY\fP][\fBKEY_LENGTH\fP]"
.br
.ti -1c
.RI "int32_t \fBdata\fP [\fBHASH_CAPACITY\fP]"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB36\fP of file \fBhash_table\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int32_t data[\fBHASH_CAPACITY\fP]"

.PP
Definition at line \fB39\fP of file \fBhash_table\&.h\fP\&.
.SS "char keys[\fBHASH_CAPACITY\fP][\fBKEY_LENGTH\fP]"

.PP
Definition at line \fB38\fP of file \fBhash_table\&.h\fP\&.
.SS "int len"

.PP
Definition at line \fB40\fP of file \fBhash_table\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
