.TH "include/dst/hash_table.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/dst/hash_table.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBHashTable\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHASH_CAPACITY\fP   30"
.br
.ti -1c
.RI "#define \fBKEY_LENGTH\fP   30"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBHashTable\fP \fBHashTable\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBHash_InitializeHashTable\fP (\fBHashTable\fP **hash)"
.br
.ti -1c
.RI "int \fBHash_DeleteHashTable\fP (\fBHashTable\fP *hash)"
.br
.ti -1c
.RI "int \fBHash_AddEntry\fP (\fBHashTable\fP *hash, const char *name, int32_t data)"
.br
.ti -1c
.RI "int \fBHash_GetIndex\fP (\fBHashTable\fP *hash, const char *key)"
.br
.ti -1c
.RI "int32_t \fBHash_GetValue\fP (\fBHashTable\fP *hash, const char *key)"
.br
.ti -1c
.RI "int \fBHash_SetValue\fP (\fBHashTable\fP *hash, const char *key, int32_t new_data)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HASH_CAPACITY   30"
\fBhash_table\&.h\fP 
.PP
\fBAuthors\fP
.RS 4
@Kevin-Caldwell
.RE
.PP
Hash Table Implementation for Storing Constants\&. Uses Dynamically allocated memory for storage
.PP
Dependencies stdlib inttypes string
.PP
Features Initialization Deletion Add Entries Get Index Get and Set Value
.PP
TODO Comments Statically Allocated Memory (High Priority) 
.PP
Definition at line \fB33\fP of file \fBhash_table\&.h\fP\&.
.SS "#define KEY_LENGTH   30"

.PP
Definition at line \fB34\fP of file \fBhash_table\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBHashTable\fP \fBHashTable\fP"

.SH "Function Documentation"
.PP 
.SS "int Hash_AddEntry (\fBHashTable\fP * hash, const char * name, int32_t data)"

.PP
Definition at line \fB15\fP of file \fBhash_table\&.c\fP\&.
.SS "int Hash_DeleteHashTable (\fBHashTable\fP * hash)"

.PP
Definition at line \fB10\fP of file \fBhash_table\&.c\fP\&.
.SS "int Hash_GetIndex (\fBHashTable\fP * hash, const char * key)"

.PP
Definition at line \fB26\fP of file \fBhash_table\&.c\fP\&.
.SS "int32_t Hash_GetValue (\fBHashTable\fP * hash, const char * key)"

.PP
Definition at line \fB39\fP of file \fBhash_table\&.c\fP\&.
.SS "int Hash_InitializeHashTable (\fBHashTable\fP ** hash)"

.PP
Definition at line \fB3\fP of file \fBhash_table\&.c\fP\&.
.SS "int Hash_SetValue (\fBHashTable\fP * hash, const char * key, int32_t new_data)"

.PP
Definition at line \fB44\fP of file \fBhash_table\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
