.TH "helperlib" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helperlib
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsign\fP (x)"
.br
.ti -1c
.RI "\fBdec_to_bin\fP (d, width)"
.br
.ti -1c
.RI "\fBbin_to_dec\fP (b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bin_to_dec ( b)"

.PP
Definition at line \fB18\fP of file \fBhelperlib\&.py\fP\&.
.SS "dec_to_bin ( d,  width)"

.PP
Definition at line \fB11\fP of file \fBhelperlib\&.py\fP\&.
.SS "sign ( x)"

.PP
Definition at line \fB4\fP of file \fBhelperlib\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
