.TH "python/helperlib.py" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/helperlib.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBhelperlib\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsign\fP (x)"
.br
.ti -1c
.RI "\fBdec_to_bin\fP (d, width)"
.br
.ti -1c
.RI "\fBbin_to_dec\fP (b)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
