.TH "image_test" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
image_test
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBload_indian_pines\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBip\fP = \fBload_indian_pines\fP()"
.br
.ti -1c
.RI "\fBwavelength\fP = \fBip\fP[0, 10, :]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "load_indian_pines ()"

.PP
Definition at line \fB4\fP of file \fBimage_test\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "ip = \fBload_indian_pines\fP()"

.PP
Definition at line \fB9\fP of file \fBimage_test\&.py\fP\&.
.SS "wavelength = \fBip\fP[0, 10, :]"

.PP
Definition at line \fB10\fP of file \fBimage_test\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
