.TH "src/image.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/image.c
.SH SYNOPSIS
.br
.PP
\fC#include 'dst/image\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBInitImage\fP (\fBimage\fP *img_p, size_t x, size_t y, size_t z)"
.br
.ti -1c
.RI "\fBPIXEL\fP \fBGetPixel\fP (\fBimage\fP *hIMG, \fBINDEX\fP x, \fBINDEX\fP y, \fBINDEX\fP z)"
.br
.ti -1c
.RI "\fBPIXEL\fP * \fBGetFrame\fP (\fBimage\fP *hIMG, \fBINDEX\fP y)"
.br
.ti -1c
.RI "void \fBSetPixel\fP (\fBimage\fP *hIMG, \fBINDEX\fP x, \fBINDEX\fP y, \fBINDEX\fP z, \fBPIXEL\fP data)"
.br
.ti -1c
.RI "int \fBImage_Equals\fP (\fBimage\fP *img1, \fBimage\fP *img2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPIXEL\fP * GetFrame (\fBimage\fP * hIMG, \fBINDEX\fP y)"

.PP
Definition at line \fB61\fP of file \fBimage\&.c\fP\&.
.SS "\fBPIXEL\fP GetPixel (\fBimage\fP * hIMG, \fBINDEX\fP x, \fBINDEX\fP y, \fBINDEX\fP z)"

.PP
Definition at line \fB55\fP of file \fBimage\&.c\fP\&.
.SS "int Image_Equals (\fBimage\fP * img1, \fBimage\fP * img2)"

.PP
Definition at line \fB71\fP of file \fBimage\&.c\fP\&.
.SS "int InitImage (\fBimage\fP * img_p, size_t x, size_t y, size_t z)"

.PP
Definition at line \fB45\fP of file \fBimage\&.c\fP\&.
.SS "void SetPixel (\fBimage\fP * hIMG, \fBINDEX\fP x, \fBINDEX\fP y, \fBINDEX\fP z, \fBPIXEL\fP data)"

.PP
Definition at line \fB66\fP of file \fBimage\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
