.TH "python/image_test.py" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/image_test.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBimage_test\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBload_indian_pines\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBip\fP = \fBload_indian_pines\fP()"
.br
.ti -1c
.RI "\fBwavelength\fP = \fBip\fP[0, 10, :]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
