.TH "include/math/linear_algebra.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/math/linear_algebra.h
.SH SYNOPSIS
.br
.PP
\fC#include 'constants/constants\&.h'\fP
.br
\fC#include 'math_functions\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAddToVector\fP(v,  other,  size)   \fBAddVectors\fP(v, other, v, size)"
.br
.ti -1c
.RI "#define \fBSubtractFromVector\fP(v,  other,  size)   \fBSubtractVectors\fP(v, other, v, size)"
.br
.ti -1c
.RI "#define \fBScalarProduct_C\fP(v,  other,  size)   \fBScalarProduct\fP(v, other, v, size)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBPIXEL\fP \fBdata_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBInitVector\fP (int32_t **v, \fBUINT\fP len)"
.br
.ti -1c
.RI "int \fBDeleteVector\fP (\fBdata_t\fP *v)"
.br
.ti -1c
.RI "int \fBAddVectors\fP (\fBdata_t\fP *v1, \fBdata_t\fP *v2, \fBdata_t\fP *res, \fBUINT\fP size)"
.br
.ti -1c
.RI "int \fBSubtractVectors\fP (\fBdata_t\fP *v1, \fBdata_t\fP *v2, \fBdata_t\fP *res, \fBUINT\fP size)"
.br
.ti -1c
.RI "int64_t \fBInnerProduct\fP (int32_t *v1, int32_t *v2, \fBUINT\fP size)"
.br
.ti -1c
.RI "int \fBScalarProduct\fP (\fBdata_t\fP *v, \fBdata_t\fP scalar, \fBdata_t\fP *res, \fBUINT\fP size)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AddToVector(v, other, size)   \fBAddVectors\fP(v, other, v, size)"

.PP
Definition at line \fB45\fP of file \fBlinear_algebra\&.h\fP\&.
.SS "#define ScalarProduct_C(v, other, size)   \fBScalarProduct\fP(v, other, v, size)"

.PP
Definition at line \fB47\fP of file \fBlinear_algebra\&.h\fP\&.
.SS "#define SubtractFromVector(v, other, size)   \fBSubtractVectors\fP(v, other, v, size)"

.PP
Definition at line \fB46\fP of file \fBlinear_algebra\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBPIXEL\fP \fBdata_t\fP"
\fBlinear_algebra\&.h\fP 
.PP
\fBAuthors\fP
.RS 4
Kevin Caldwell @BrianShTsoi
.RE
.PP
Skeleton File for Generic Vector Operations\&.
.PP
Features Initialization Deletion Addition Subtraction Scalar Product Inner Product (Dot Product)
.PP
Uses Local Difference Vector Weight Vector
.PP
Dependencies \fBconstants\&.h\fP \fBmath_functions\&.h\fP 
.PP
Definition at line \fB30\fP of file \fBlinear_algebra\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int AddVectors (\fBdata_t\fP * v1, \fBdata_t\fP * v2, \fBdata_t\fP * res, \fBUINT\fP size)"

.PP
Definition at line \fB14\fP of file \fBlinear_algebra\&.c\fP\&.
.SS "int DeleteVector (\fBdata_t\fP * v)"

.PP
Definition at line \fB9\fP of file \fBlinear_algebra\&.c\fP\&.
.SS "int InitVector (int32_t ** v, \fBUINT\fP len)"

.PP
Definition at line \fB3\fP of file \fBlinear_algebra\&.c\fP\&.
.SS "int64_t InnerProduct (int32_t * v1, int32_t * v2, \fBUINT\fP size)"

.PP
Definition at line \fB28\fP of file \fBlinear_algebra\&.c\fP\&.
.SS "int ScalarProduct (\fBdata_t\fP * v, \fBdata_t\fP scalar, \fBdata_t\fP * res, \fBUINT\fP size)"

.PP
Definition at line \fB37\fP of file \fBlinear_algebra\&.c\fP\&.
.SS "int SubtractVectors (\fBdata_t\fP * v1, \fBdata_t\fP * v2, \fBdata_t\fP * res, \fBUINT\fP size)"

.PP
Definition at line \fB21\fP of file \fBlinear_algebra\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
