.TH "include/predictor/local_differences.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/predictor/local_differences.h
.SH SYNOPSIS
.br
.PP
\fC#include 'constants/constants\&.h'\fP
.br
\fC#include 'math/linear_algebra\&.h'\fP
.br
\fC#include 'math/math_functions\&.h'\fP
.br
\fC#include 'predictor/local_sum\&.h'\fP
.br
\fC#include 'predictor/sample_representative\&.h'\fP
.br
\fC#include 'predictor/weights\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPs\fP(z)   \fBMIN\fP(z, \fBkP\fP)"
.br
.ti -1c
.RI "#define \fBDLD\fP(hIMG,  z,  y,  x,  d)   \fBDirectionalLocalDifference\fP(hIMG, z,y,x,d)"
.br
.ti -1c
.RI "#define \fBDLD_N\fP(hIMG,  z,  y,  x)   \fBDirectionalLocalDifference\fP(hIMG, z,y,x,\fBN\fP)"
.br
.ti -1c
.RI "#define \fBDLD_W\fP(hIMG,  z,  y,  x)   \fBDirectionalLocalDifference\fP(hIMG, z,y,x,\fBW\fP)"
.br
.ti -1c
.RI "#define \fBDLD_NW\fP(hIMG,  z,  y,  x)   \fBDirectionalLocalDifference\fP(hIMG, z,y,x,\fBNW\fP)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDIRECTION\fP { \fBN\fP = 0, \fBW\fP, \fBNW\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBCentralLocalDifference\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.ti -1c
.RI "int32_t \fBDirectionalLocalDifference\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int direction)"
.br
.ti -1c
.RI "int \fBLocalDirectionVector\fP (\fBimage\fP *hIMG, int32_t **local_direction_vector, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.ti -1c
.RI "int64_t \fBPredictedCentralLocalDifference\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DLD(hIMG, z, y, x, d)   \fBDirectionalLocalDifference\fP(hIMG, z,y,x,d)"

.PP
Definition at line \fB23\fP of file \fBlocal_differences\&.h\fP\&.
.SS "#define DLD_N(hIMG, z, y, x)   \fBDirectionalLocalDifference\fP(hIMG, z,y,x,\fBN\fP)"

.PP
Definition at line \fB24\fP of file \fBlocal_differences\&.h\fP\&.
.SS "#define DLD_NW(hIMG, z, y, x)   \fBDirectionalLocalDifference\fP(hIMG, z,y,x,\fBNW\fP)"

.PP
Definition at line \fB26\fP of file \fBlocal_differences\&.h\fP\&.
.SS "#define DLD_W(hIMG, z, y, x)   \fBDirectionalLocalDifference\fP(hIMG, z,y,x,\fBW\fP)"

.PP
Definition at line \fB25\fP of file \fBlocal_differences\&.h\fP\&.
.SS "#define Ps(z)   \fBMIN\fP(z, \fBkP\fP)"
\fBlocal_differences\&.h\fP 
.PP
\fBAuthors\fP
.RS 4
@Kevin-Caldwell @BrianShTsoi
.RE
.PP
Central and Directional Local Difference Functions and Definitions 
.PP
Definition at line \fB19\fP of file \fBlocal_differences\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDIRECTION\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIN \fP\fP
.TP
\fB\fIW \fP\fP
.TP
\fB\fINW \fP\fP
.PP
Definition at line \fB21\fP of file \fBlocal_differences\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int32_t CentralLocalDifference (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB3\fP of file \fBlocal_differences\&.c\fP\&.
.SS "int32_t DirectionalLocalDifference (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int direction)"

.PP
Definition at line \fB8\fP of file \fBlocal_differences\&.c\fP\&.
.SS "int LocalDirectionVector (\fBimage\fP * hIMG, int32_t ** local_direction_vector, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB55\fP of file \fBlocal_differences\&.c\fP\&.
.SS "int64_t PredictedCentralLocalDifference (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB82\fP of file \fBlocal_differences\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
