.TH "src/local_differences.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/local_differences.c
.SH SYNOPSIS
.br
.PP
\fC#include 'predictor/local_differences\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBCentralLocalDifference\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.ti -1c
.RI "int32_t \fBDirectionalLocalDifference\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int direction)"
.br
.ti -1c
.RI "int \fBLocalDirectionVector\fP (\fBimage\fP *hIMG, int32_t **local_direction_vector, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.ti -1c
.RI "int64_t \fBPredictedCentralLocalDifference\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int32_t CentralLocalDifference (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB3\fP of file \fBlocal_differences\&.c\fP\&.
.SS "int32_t DirectionalLocalDifference (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int direction)"

.PP
Definition at line \fB8\fP of file \fBlocal_differences\&.c\fP\&.
.SS "int LocalDirectionVector (\fBimage\fP * hIMG, int32_t ** local_direction_vector, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB55\fP of file \fBlocal_differences\&.c\fP\&.
.SS "int64_t PredictedCentralLocalDifference (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB82\fP of file \fBlocal_differences\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
