.TH "src/local_sum.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/local_sum.c
.SH SYNOPSIS
.br
.PP
\fC#include 'predictor/local_sum\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBFindLocalSum\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t FindLocalSum (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB4\fP of file \fBlocal_sum\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
