.TH "src/logs.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/logs.c
.SH SYNOPSIS
.br
.PP
\fC#include 'files/logs\&.h'\fP
.br
\fC#include 'constants/global_constants\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fB_GET_PRINT_TIME\fP ()"
.br
.ti -1c
.RI "void \fBLog_init\fP ()"
.br
.ti -1c
.RI "void \fBLog_close\fP ()"
.br
.ti -1c
.RI "void \fBLog_add\fP (const char *text)"
.br
.ti -1c
.RI "void \fBLog_error\fP (char *text)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBlog_file\fP [] = 'data/logs/compressor\&.logs'"
.br
.ti -1c
.RI "char \fB_time_str\fP [100]"
.br
.ti -1c
.RI "\fBfile_t\fP * \fBlog_fptr\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * _GET_PRINT_TIME ()"

.PP
Definition at line \fB9\fP of file \fBlogs\&.c\fP\&.
.SS "void Log_add (const char * text)"

.PP
Definition at line \fB34\fP of file \fBlogs\&.c\fP\&.
.SS "void Log_close ()"

.PP
Definition at line \fB29\fP of file \fBlogs\&.c\fP\&.
.SS "void Log_error (char * text)"

.PP
Definition at line \fB38\fP of file \fBlogs\&.c\fP\&.
.SS "void Log_init ()"

.PP
Definition at line \fB17\fP of file \fBlogs\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char _time_str[100]"

.PP
Definition at line \fB7\fP of file \fBlogs\&.c\fP\&.
.SS "char log_file[] = 'data/logs/compressor\&.logs'"

.PP
Definition at line \fB6\fP of file \fBlogs\&.c\fP\&.
.SS "\fBfile_t\fP* log_fptr"

.PP
Definition at line \fB15\fP of file \fBlogs\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
