.TH "include/files/logs.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/files/logs.h
.SH SYNOPSIS
.br
.PP
\fC#include 'file_IO\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLog_init\fP ()"
.br
.ti -1c
.RI "void \fBLog_close\fP ()"
.br
.ti -1c
.RI "void \fBLog_add\fP (const char *text)"
.br
.ti -1c
.RI "void \fBLog_error\fP (char *text)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Log_add (const char * text)"

.PP
Definition at line \fB34\fP of file \fBlogs\&.c\fP\&.
.SS "void Log_close ()"

.PP
Definition at line \fB29\fP of file \fBlogs\&.c\fP\&.
.SS "void Log_error (char * text)"

.PP
Definition at line \fB38\fP of file \fBlogs\&.c\fP\&.
.SS "void Log_init ()"

.PP
Definition at line \fB17\fP of file \fBlogs\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
