.TH "python/mat_to_csv.py" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/mat_to_csv.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmat_to_csv\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBload_pic\fP (file_name, header='indian_pines')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBargS\fP = sys\&.argv"
.br
.ti -1c
.RI "\fBNx\fP = int(\fBargS\fP[4])"
.br
.ti -1c
.RI "\fBNy\fP = int(\fBargS\fP[5])"
.br
.ti -1c
.RI "\fBNz\fP = int(\fBargS\fP[6])"
.br
.ti -1c
.RI "\fBdata\fP = \fBload_pic\fP(\fBargS\fP[1], \fBargS\fP[2])[:\fBNx\fP, :\fBNy\fP, :\fBNz\fP]"
.br
.ti -1c
.RI "\fBn\fP = int(\fBargS\fP[4])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
