.TH "src/math_functions.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/math_functions.c
.SH SYNOPSIS
.br
.PP
\fC#include 'math/math_functions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUINT\fP \fBEuclidian2\fP (\fBdim2\fP pt1, \fBdim2\fP pt2)"
.br
.ti -1c
.RI "\fBUINT\fP \fBEuclidian3\fP (\fBdim3\fP pt1, \fBdim3\fP pt2)"
.br
.ti -1c
.RI "\fBUINT\fP \fBManhattan2\fP (\fBdim2\fP pt1, \fBdim2\fP pt2)"
.br
.ti -1c
.RI "\fBUINT\fP \fBManhattan3\fP (\fBdim3\fP pt1, \fBdim3\fP pt2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBUINT\fP Euclidian2 (\fBdim2\fP pt1, \fBdim2\fP pt2)"

.PP
Definition at line \fB3\fP of file \fBmath_functions\&.c\fP\&.
.SS "\fBUINT\fP Euclidian3 (\fBdim3\fP pt1, \fBdim3\fP pt2)"

.PP
Definition at line \fB7\fP of file \fBmath_functions\&.c\fP\&.
.SS "\fBUINT\fP Manhattan2 (\fBdim2\fP pt1, \fBdim2\fP pt2)"

.PP
Definition at line \fB11\fP of file \fBmath_functions\&.c\fP\&.
.SS "\fBUINT\fP Manhattan3 (\fBdim3\fP pt1, \fBdim3\fP pt2)"

.PP
Definition at line \fB15\fP of file \fBmath_functions\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
