.TH "python/perlin_image.py" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/perlin_image.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBperlin_image\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinterpolant\fP (t)"
.br
.ti -1c
.RI "\fBgenerate_perlin_noise_3d\fP (shape, res, tileable=(False, False, False), \fBinterpolant\fP=\fBinterpolant\fP)"
.br
.ti -1c
.RI "\fBgenerate_fractal_noise_3d\fP (shape, res, octaves=1, persistence=0\&.5, lacunarity=2, tileable=(False, False, False), \fBinterpolant\fP=\fBinterpolant\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
