.TH "include/testing/perlin.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/testing/perlin.h
.SH SYNOPSIS
.br
.PP
\fC#include 'dst/image\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBGeneratePerlinImage\fP (\fBdim3\fP size, int index, int length)"
.br
.ti -1c
.RI "void \fBPerlin4\fP (\fBimage\fP *result, int cube_side)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void GeneratePerlinImage (\fBdim3\fP size, int index, int length)"

.PP
Definition at line \fB103\fP of file \fBperlin_noise\&.c\fP\&.
.SS "void Perlin4 (\fBimage\fP * result, int cube_side)"

.PP
Definition at line \fB75\fP of file \fBperlin_noise\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
