.TH "src/predictor.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/predictor.c
.SH SYNOPSIS
.br
.PP
\fC#include 'constants/global_constants\&.h'\fP
.br
\fC#include 'predictor/predictor\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'files/logs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPredict\fP (\fBimage\fP *hIMG, \fBimage\fP *result, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.ti -1c
.RI "int \fBRunPredictor\fP (\fBimage\fP *hIMG, \fBimage\fP *result)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfile_t\fP * \fBfp\fP"
.br
.ti -1c
.RI "int \fBC\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Predict (\fBimage\fP * hIMG, \fBimage\fP * result, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB10\fP of file \fBpredictor\&.c\fP\&.
.SS "int RunPredictor (\fBimage\fP * hIMG, \fBimage\fP * result)"

.PP
Definition at line \fB57\fP of file \fBpredictor\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int C = 0"

.PP
Definition at line \fB8\fP of file \fBpredictor\&.c\fP\&.
.SS "\fBfile_t\fP* fp"

.PP
Definition at line \fB7\fP of file \fBpredictor\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
