.TH "python/predictor_eg.py" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/predictor_eg.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpredictor_eg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBn\fP = len(sys\&.argv)"
.br
.ti -1c
.RI "\fBdata\fP = ReadCSV(sys\&.argv[1])"
.br
.ti -1c
.RI "\fBNx\fP"
.br
.ti -1c
.RI "\fBNy\fP"
.br
.ti -1c
.RI "\fBNz\fP"
.br
.ti -1c
.RI "\fBpython_predicted\fP = comp\&.predictor(\fBdata\fP)"
.br
.ti -1c
.RI "\fBencoded\fP = comp\&.predictor(\fBpython_predicted\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
