.TH "predictor_eg" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predictor_eg
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBn\fP = len(sys\&.argv)"
.br
.ti -1c
.RI "\fBdata\fP = ReadCSV(sys\&.argv[1])"
.br
.ti -1c
.RI "\fBNx\fP"
.br
.ti -1c
.RI "\fBNy\fP"
.br
.ti -1c
.RI "\fBNz\fP"
.br
.ti -1c
.RI "\fBpython_predicted\fP = comp\&.predictor(\fBdata\fP)"
.br
.ti -1c
.RI "\fBencoded\fP = comp\&.predictor(\fBpython_predicted\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "data = ReadCSV(sys\&.argv[1])"

.PP
Definition at line \fB12\fP of file \fBpredictor_eg\&.py\fP\&.
.SS "encoded = comp\&.predictor(\fBpython_predicted\fP)"

.PP
Definition at line \fB21\fP of file \fBpredictor_eg\&.py\fP\&.
.SS "n = len(sys\&.argv)"

.PP
Definition at line \fB10\fP of file \fBpredictor_eg\&.py\fP\&.
.SS "Nx"

.PP
Definition at line \fB13\fP of file \fBpredictor_eg\&.py\fP\&.
.SS "Ny"

.PP
Definition at line \fB13\fP of file \fBpredictor_eg\&.py\fP\&.
.SS "Nz"

.PP
Definition at line \fB13\fP of file \fBpredictor_eg\&.py\fP\&.
.SS "python_predicted = comp\&.predictor(\fBdata\fP)"

.PP
Definition at line \fB15\fP of file \fBpredictor_eg\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
