.TH "PredictorCache" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PredictorCache \- Struct \fBPredictorCache\fP is a struct for storing the intermediate results obtained through the predictor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cache_predictor\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBimage\fP * \fBcache_space\fP [1]"
.br
.ti -1c
.RI "int32_t * \fBweights\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct \fBPredictorCache\fP is a struct for storing the intermediate results obtained through the predictor\&. 

cache_space: dynamically allocated image array for storing multiple images
.PP
weights: dynamcially allocated int32_t array for storing the weights
.PP
\fBDeprecated\fP
.RS 4
The Predictor testing has been re-implemented to accomodate more streamlined and memory-efficient debugging processes\&.
.RE
.PP
.PP
See \fBpredictor\&.c\fP for more details 
.PP
Definition at line \fB32\fP of file \fBcache_predictor\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBimage\fP* cache_space[1]"

.PP
Definition at line \fB33\fP of file \fBcache_predictor\&.h\fP\&.
.SS "int32_t* weights"

.PP
Definition at line \fB34\fP of file \fBcache_predictor\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
