.TH "src/sample_representative.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sample_representative.c
.SH SYNOPSIS
.br
.PP
\fC#include 'predictor/sample_representative\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdata_t\fP \fBSampleRepresentative\fP (uint16_t sample_value)"
.br
.ti -1c
.RI "uint16_t \fBPredictedSample\fP (uint32_t double_resolution_predicted_sample)"
.br
.ti -1c
.RI "uint32_t \fBDoubleResolutionPredictedSample\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int64_t high_resolution_predicted_sample)"
.br
.ti -1c
.RI "int64_t \fBHighResolutionPredictedSample\fP (int64_t predicted_central_local_difference, uint32_t local_sum)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t DoubleResolutionPredictedSample (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int64_t high_resolution_predicted_sample)"

.PP
Definition at line \fB13\fP of file \fBsample_representative\&.c\fP\&.
.SS "int64_t HighResolutionPredictedSample (int64_t predicted_central_local_difference, uint32_t local_sum)"

.PP
Definition at line \fB27\fP of file \fBsample_representative\&.c\fP\&.
.SS "uint16_t PredictedSample (uint32_t double_resolution_predicted_sample)"

.PP
Definition at line \fB9\fP of file \fBsample_representative\&.c\fP\&.
.SS "\fBdata_t\fP SampleRepresentative (uint16_t sample_value)"

.PP
Definition at line \fB5\fP of file \fBsample_representative\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
