.TH "include/predictor/sample_representative.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/predictor/sample_representative.h
.SH SYNOPSIS
.br
.PP
\fC#include 'dst/image\&.h'\fP
.br
\fC#include 'constants/constants\&.h'\fP
.br
\fC#include 'cache/cache_predictor\&.h'\fP
.br
\fC#include 'math/linear_algebra\&.h'\fP
.br
\fC#include 'predictor/local_differences\&.h'\fP
.br
\fC#include 'predictor/quantizer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSR\fP(hIMG,  Z,  Y,  X)   \fBGetPixel\fP(hIMG, X,Y,Z)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdata_t\fP \fBSampleRepresentative\fP (uint16_t sample_value)"
.br
.ti -1c
.RI "uint32_t \fBDoubleResolutionPredictedSample\fP (\fBimage\fP *hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int64_t high_resolution_predicted_sample)"
.br
.ti -1c
.RI "uint16_t \fBPredictedSample\fP (uint32_t double_resolution_predicted_sample)"
.br
.ti -1c
.RI "int64_t \fBHighResolutionPredictedSample\fP (int64_t predicted_central_local_difference, uint32_t local_sum)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdata_t\fP \fBdamping\fP []"
.br
.ti -1c
.RI "\fBdata_t\fP \fBoffset\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SR(hIMG, Z, Y, X)   \fBGetPixel\fP(hIMG, X,Y,Z)"
\fBsample_representative\&.h\fP 
.PP
\fBAuthors\fP
.RS 4
@Kevin-Caldwell @BrianShTsoi
.RE
.PP
A collection of Sample representative calculation functions\&. 
.PP
Definition at line \fB21\fP of file \fBsample_representative\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "uint32_t DoubleResolutionPredictedSample (\fBimage\fP * hIMG, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int64_t high_resolution_predicted_sample)"

.PP
Definition at line \fB13\fP of file \fBsample_representative\&.c\fP\&.
.SS "int64_t HighResolutionPredictedSample (int64_t predicted_central_local_difference, uint32_t local_sum)"

.PP
Definition at line \fB27\fP of file \fBsample_representative\&.c\fP\&.
.SS "uint16_t PredictedSample (uint32_t double_resolution_predicted_sample)"

.PP
Definition at line \fB9\fP of file \fBsample_representative\&.c\fP\&.
.SS "\fBdata_t\fP SampleRepresentative (uint16_t sample_value)"

.PP
Definition at line \fB5\fP of file \fBsample_representative\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBdata_t\fP damping[]\fC [extern]\fP"

.SS "\fBdata_t\fP offset[]\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
