.TH "include/encoder/stream_encoder.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/encoder/stream_encoder.h
.SH SYNOPSIS
.br
.PP
\fC#include <inttypes\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'files/file_IO\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBVarIntFileStream\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBL_SHIFT\fP(x,  s)   (s < 0 ? x >> \-s : x << s)"
.br
.ti -1c
.RI "#define \fBBUFFER_REG_SIZE\fP   32"
.br
.ti -1c
.RI "#define \fBBUFFER_LENGTH\fP   15"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBVarIntFileStream\fP \fBVIFS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeVarIntStream\fP (\fBVIFS\fP *stream, const char *file_name, uint32_t buffer_size)"
.br
.ti -1c
.RI "void \fBStreamVarInteger\fP (\fBVIFS\fP *stream, uint32_t data, uint32_t length)"
.br
.ti -1c
.RI "void \fBCloseVarIntegerStream\fP (\fBVIFS\fP *stream)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFER_LENGTH   15"

.PP
Definition at line \fB18\fP of file \fBstream_encoder\&.h\fP\&.
.SS "#define BUFFER_REG_SIZE   32"

.PP
Definition at line \fB17\fP of file \fBstream_encoder\&.h\fP\&.
.SS "#define L_SHIFT(x, s)   (s < 0 ? x >> \-s : x << s)"
\fBstream_encoder\&.h\fP 
.PP
\fBAuthor\fP
.RS 4
@Kevin-Caldwell
.RE
.PP
\fBDeprecated\fP
.RS 4
Replaced by \fBvarIntFile_IO\&.h\fP 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBstream_encoder\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBVarIntFileStream\fP \fBVIFS\fP"

.SH "Function Documentation"
.PP 
.SS "void CloseVarIntegerStream (\fBVIFS\fP * stream)"

.PP
Definition at line \fB38\fP of file \fBstream_encoder\&.c\fP\&.
.SS "void InitializeVarIntStream (\fBVIFS\fP * stream, const char * file_name, uint32_t buffer_size)"

.PP
Definition at line \fB3\fP of file \fBstream_encoder\&.c\fP\&.
.SS "void StreamVarInteger (\fBVIFS\fP * stream, uint32_t data, uint32_t length)"

.PP
Definition at line \fB12\fP of file \fBstream_encoder\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
