.TH "TestComp" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestComp
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUpClass\fP (cls)"
.br
.ti -1c
.RI "\fBtest_CSV\fP (self)"
.br
.ti -1c
.RI "\fBtest_predictor\fP (self)"
.br
.ti -1c
.RI "\fBtest_unpredict\fP (self)"
.br
.ti -1c
.RI "\fBtest_inv_GPO2\fP (self)"
.br
.ti -1c
.RI "\fBtest_decompress\fP (self)"
.br
.ti -1c
.RI "\fBtest_compression_algo\fP (self)"
.br
.ti -1c
.RI "\fBtest_rmse\fP (self)"
.br
.ti -1c
.RI "\fBtest_compression_ratio\fP (self)"
.br
.ti -1c
.RI "\fBload_pic\fP (file_name='python/images/Indian_pines\&.mat', header='indian_pines')"
.br
.ti -1c
.RI "\fBrmse\fP (self, \fBdata\fP, decompressed)"
.br
.ti -1c
.RI "\fBcompression_ratio\fP (self, \fBdata\fP, compressed)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdata\fP"
.br
.ti -1c
.RI "\fBNx\fP"
.br
.ti -1c
.RI "\fBNy\fP"
.br
.ti -1c
.RI "\fBNz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBtest_compression\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "compression_ratio ( self,  data,  compressed)"

.PP
Definition at line \fB112\fP of file \fBtest_compression\&.py\fP\&.
.SS "load_pic ( file_name = \fC'python/images/Indian_pines\&.mat'\fP,  header = \fC'indian_pines'\fP)"

.PP
Definition at line \fB94\fP of file \fBtest_compression\&.py\fP\&.
.SS "rmse ( self,  data,  decompressed)"

.PP
Definition at line \fB102\fP of file \fBtest_compression\&.py\fP\&.
.SS "setUpClass ( cls)"

.PP
Definition at line \fB11\fP of file \fBtest_compression\&.py\fP\&.
.SS "test_compression_algo ( self)"

.PP
Definition at line \fB62\fP of file \fBtest_compression\&.py\fP\&.
.SS "test_compression_ratio ( self)"

.PP
Definition at line \fB79\fP of file \fBtest_compression\&.py\fP\&.
.SS "test_CSV ( self)"

.PP
Definition at line \fB23\fP of file \fBtest_compression\&.py\fP\&.
.SS "test_decompress ( self)"

.PP
Definition at line \fB57\fP of file \fBtest_compression\&.py\fP\&.
.SS "test_inv_GPO2 ( self)"

.PP
Definition at line \fB45\fP of file \fBtest_compression\&.py\fP\&.
.SS "test_predictor ( self)"

.PP
Definition at line \fB30\fP of file \fBtest_compression\&.py\fP\&.
.SS "test_rmse ( self)"

.PP
Definition at line \fB69\fP of file \fBtest_compression\&.py\fP\&.
.SS "test_unpredict ( self)"

.PP
Definition at line \fB40\fP of file \fBtest_compression\&.py\fP\&.
.SH "Field Documentation"
.PP 
.SS "data"

.PP
Definition at line \fB17\fP of file \fBtest_compression\&.py\fP\&.
.SS "Nx"

.PP
Definition at line \fB19\fP of file \fBtest_compression\&.py\fP\&.
.SS "Ny"

.PP
Definition at line \fB20\fP of file \fBtest_compression\&.py\fP\&.
.SS "Nz"

.PP
Definition at line \fB21\fP of file \fBtest_compression\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
