.TH "src/test_UHI.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test_UHI.c
.SH SYNOPSIS
.br
.PP
\fC#include 'testing/test_UHI\&.h'\fP
.br
\fC#include 'testing/synthetic_image_generator\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtest_UHI\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int test_UHI ()"

.PP
Definition at line \fB5\fP of file \fBtest_UHI\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
