.TH "src/test_varInt.c" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test_varInt.c
.SH SYNOPSIS
.br
.PP
\fC#include 'testing/test_varInt\&.h'\fP
.br
\fC#include 'files/logs\&.h'\fP
.br
\fC#include 'constants/global_constants\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintBits\fP (size_t const size, void const *const ptr)"
.br
.ti -1c
.RI "void \fBprint_buffer\fP (\fBVUF\fP *f)"
.br
.ti -1c
.RI "int \fBtestVUF_Write\fP ()"
.br
.ti -1c
.RI "int \fBtestVUF_Read\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void print_buffer (\fBVUF\fP * f)"

.PP
Definition at line \fB20\fP of file \fBtest_varInt\&.c\fP\&.
.SS "void printBits (size_t const size, void const *const ptr)"

.PP
Definition at line \fB5\fP of file \fBtest_varInt\&.c\fP\&.
.SS "int testVUF_Read ()"

.PP
Definition at line \fB65\fP of file \fBtest_varInt\&.c\fP\&.
.SS "int testVUF_Write ()"

.PP
Definition at line \fB36\fP of file \fBtest_varInt\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
