.TH "include/testing/test_varInt.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/testing/test_varInt.h
.SH SYNOPSIS
.br
.PP
\fC#include 'files/varIntFile_IO\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtestVUF_Write\fP ()"
.br
.ti -1c
.RI "int \fBtestVUF_Read\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int testVUF_Read ()"

.PP
Definition at line \fB65\fP of file \fBtest_varInt\&.c\fP\&.
.SS "int testVUF_Write ()"

.PP
Definition at line \fB36\fP of file \fBtest_varInt\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
