.TH "VarIntFileStream" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VarIntFileStream
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stream_encoder\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfile_t\fP * \fBfs\fP"
.br
.ti -1c
.RI "int32_t \fBbit_ptr\fP"
.br
.ti -1c
.RI "uint32_t \fBbyte_ptr\fP"
.br
.ti -1c
.RI "uint32_t \fBbuffer\fP [\fBBUFFER_LENGTH\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBstream_encoder\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int32_t bit_ptr"

.PP
Definition at line \fB24\fP of file \fBstream_encoder\&.h\fP\&.
.SS "uint32_t buffer[\fBBUFFER_LENGTH\fP]"

.PP
Definition at line \fB27\fP of file \fBstream_encoder\&.h\fP\&.
.SS "uint32_t byte_ptr"

.PP
Definition at line \fB25\fP of file \fBstream_encoder\&.h\fP\&.
.SS "\fBfile_t\fP* fs"

.PP
Definition at line \fB22\fP of file \fBstream_encoder\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
