.TH "VarUnsignedIntFile" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VarUnsignedIntFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <varIntFile_IO\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfile_t\fP * \fBfs\fP"
.br
.ti -1c
.RI "uint32_t \fBrw_buffer\fP [\fBBUFFER_LENGTH\fP]"
.br
.ti -1c
.RI "char \fBio_mode\fP"
.br
.ti -1c
.RI "int8_t \fBbit_index\fP"
.br
.ti -1c
.RI "int8_t \fBbyte_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manages VUF files\&.
.PP
Variable Unsigned Files are designed to store integers of all sizes less than 32 bits and greater than 0 bits\&. 
.PP
Definition at line \fB32\fP of file \fBvarIntFile_IO\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int8_t bit_index"

.PP
Definition at line \fB37\fP of file \fBvarIntFile_IO\&.h\fP\&.
.SS "int8_t byte_index"

.PP
Definition at line \fB38\fP of file \fBvarIntFile_IO\&.h\fP\&.
.SS "\fBfile_t\fP* fs"

.PP
Definition at line \fB33\fP of file \fBvarIntFile_IO\&.h\fP\&.
.SS "char io_mode"

.PP
Definition at line \fB35\fP of file \fBvarIntFile_IO\&.h\fP\&.
.SS "uint32_t rw_buffer[\fBBUFFER_LENGTH\fP]"

.PP
Definition at line \fB34\fP of file \fBvarIntFile_IO\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
