.TH "include/predictor/weights.h" 3 "Version 1.0" "Hyperspectral Image Compression" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/predictor/weights.h
.SH SYNOPSIS
.br
.PP
\fC#include 'constants/constants\&.h'\fP
.br
\fC#include 'dst/image\&.h'\fP
.br
\fC#include 'math/linear_algebra\&.h'\fP
.br
\fC#include 'predictor/quantizer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPs\fP(z)   \fBMIN\fP(z, \fBkP\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBInitializeWeights\fP (int32_t **weight_ptr, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"
.br
.ti -1c
.RI "int32_t \fBDoubleResolutionPredictionError\fP (int16_t clipped_quantizer_bin_center, int32_t double_resolution_predicted_sample)"
.br
.ti -1c
.RI "int32_t \fBWeightUpdateScalingExponent\fP (\fBINDEX\fP y, \fBINDEX\fP x)"
.br
.ti -1c
.RI "int \fBUpdateWeights\fP (\fBimage\fP *hIMG, int32_t *weights, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int32_t double_resolution_prediction_error)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Ps(z)   \fBMIN\fP(z, \fBkP\fP)"
\fBweights\&.h\fP 
.PP
\fBAuthor\fP
.RS 4
@Kevin-Caldwell
.RE
.PP
Functions for Initializing, Calculating and Updating Weights for Predictor and Reconstructor\&. 
.PP
Definition at line \fB18\fP of file \fBweights\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int32_t DoubleResolutionPredictionError (int16_t clipped_quantizer_bin_center, int32_t double_resolution_predicted_sample)"

.PP
Definition at line \fB35\fP of file \fBweights\&.c\fP\&.
.SS "int InitializeWeights (int32_t ** weight_ptr, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB4\fP of file \fBweights\&.c\fP\&.
.SS "int UpdateWeights (\fBimage\fP * hIMG, int32_t * weights, \fBINDEX\fP z, \fBINDEX\fP y, \fBINDEX\fP x, int32_t double_resolution_prediction_error)"

.PP
Definition at line \fB50\fP of file \fBweights\&.c\fP\&.
.SS "int32_t WeightUpdateScalingExponent (\fBINDEX\fP y, \fBINDEX\fP x)"

.PP
Definition at line \fB41\fP of file \fBweights\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hyperspectral Image Compression from the source code\&.
