linear_algebra.c
int InitVector(int32_t **v, UINT len)
Referenced by InitializeWeights, LocalDirectionVector.
int DeleteVector(data_t *v)
int AddVectors(data_t *v1, data_t *v2, data_t *res, UINT size)
int SubtractVectors(data_t *v1, data_t *v2, data_t *res, UINT size)
int64_t InnerProduct(int32_t *v1, int32_t *v2, UINT size)
Referenced by PredictedCentralLocalDifference.
int ScalarProduct(data_t *v, data_t scalar, data_t *res, UINT size)