sample_representative.h
SR
sample_representative.h @Kevin-Caldwell @BrianShTsoi A collection of Sample representative calculation functions.
data_t damping[][]
data_t offset[][]
Referenced by F_SEEK.
data_t SampleRepresentative(uint16_t sample_value)
uint32_t DoubleResolutionPredictedSample(image *hIMG, INDEX z, INDEX y, INDEX x, int64_t high_resolution_predicted_sample)
References BPOW, kP, kSmid, Omega, S.
Referenced by Predict, ReconstructPixel.
uint16_t PredictedSample(uint32_t double_resolution_predicted_sample)
Referenced by Predict, ReconstructPixel.
int64_t HighResolutionPredictedSample(int64_t predicted_central_local_difference, uint32_t local_sum)
References BPOW, CLIP, kR, kSmax, kSmid, kSmin, Omega.
Referenced by Predict, ReconstructPixel.