linear_algebra.h
AddToVector
SubtractFromVector
ScalarProduct_C
typedef PIXEL data_t
linear_algebra.h Kevin Caldwell @BrianShTsoi Skeleton File for Generic Vector Operations. Features Initialization Deletion Addition Subtraction Scalar Product Inner Product (Dot Product) Uses Local Difference Vector Weight Vector Dependencies constants.h math_functions.h
int InitVector(int32_t **v, UINT len)
Referenced by InitializeWeights, LocalDirectionVector.
int DeleteVector(data_t *v)
int AddVectors(data_t *v1, data_t *v2, data_t *res, UINT size)
int SubtractVectors(data_t *v1, data_t *v2, data_t *res, UINT size)
int64_t InnerProduct(int32_t *v1, int32_t *v2, UINT size)
Referenced by PredictedCentralLocalDifference.
int ScalarProduct(data_t *v, data_t scalar, data_t *res, UINT size)