generate_image.h
void TestHeader()
References PrepareImageMetadata, PreparePredictorMetadata, PrepareSampleAdaptiveEntropyCoder.
void TestReadImage()
References ReadImageFromCSV, SaveImageAsCSV.
int PredictImage(char *source, char *destination)
References image::data, DeletePredictorCache, global_cache, InitializePredictorCache, InitImage, Log_add, Log_error, ReadImageFromCSV, RunPredictor, SaveImageAsCSV, image::size, dim3::x, dim3::y, dim3::z.
Referenced by main.
int EncodeImage(char *source, char *destination)
References image::data, EncodeBody, InitalizeImageConstants, InitalizePredictorConstants, LoadConstantFile, predictor_constants, ReadImageFromCSV, RES_OK, image::size.
Referenced by main.
int CompressImage(char *source, char *destination)
Referenced by main.
int GenerateVoronoiImage(dim3 size, int index, int points)
References image::data, GenerateVoronoiFlat3DLocal, InitImage, RES_OK, SaveImageAsCSV, dim3::x, dim3::y, dim3::z.
Referenced by main.