cache_predictor.c
PredictorCache* global_cache
Referenced by Predict, PredictedCentralLocalDifference, PredictImage, ReconstructPixel, TestReconstructor.
char* CacheFiles[][]
int InitializePredictorCache(PredictorCache **ptr_p_cache, image *hIMG)
References PredictorCache::cache_space, InitializeWeights, InitImage, image::size, PredictorCache::weights, dim3::x, dim3::y, dim3::z.
Referenced by PredictImage, TestReconstructor.
int DeletePredictorCache(PredictorCache *p_cache)
References PredictorCache::cache_space.
Referenced by PredictImage.