image.c
int InitImage(image *img_p, size_t x, size_t y, size_t z)
References image::data, image::size, dim3::x, dim3::y, dim3::z.
Referenced by GeneratePerlinImage, GenerateVoronoiImage, InitializePredictorCache, PredictImage, ReadImageFromCSV, test_UHI, TestReconstructor.
PIXEL GetPixel(image *hIMG, INDEX x, INDEX y, INDEX z)
References image::data, MAP3_1, image::size.
Referenced by EncodeBody, Predict, ReconstructPixel, SaveImageAsCSV, test_UHI.
PIXEL * GetFrame(image *hIMG, INDEX y)
References image::data, FRAME_SIZE, image::size.
void SetPixel(image *hIMG, INDEX x, INDEX y, INDEX z, PIXEL data)
References image::data, MAP3_1, image::size.
Referenced by Decoder_DecodeBody, GenerateVoronoiFlat3DLocal, GenerateVoronoiFlat3DNaive, Perlin4, Predict, ReconstructPixel, ShadeVoronoiBox3.
int Image_Equals(image *img1, image *img2)
References image::data, image::size, dim3::x, dim3::y, dim3::z.
Referenced by TestReconstructor.