stream_encoder.h
L_SHIFT
stream_encoder.h Kevin Caldwell DeprecatedReplaced by varIntFile_IO.h
BUFFER_REG_SIZE
BUFFER_LENGTH
typedef struct VarIntFileStream VIFS
void InitializeVarIntStream(VIFS *stream, const char *file_name, uint32_t buffer_size)
References VarIntFileStream::bit_ptr, VarIntFileStream::byte_ptr, F_OPEN, VarIntFileStream::fs, WRITE.
Referenced by EncodeBody.
void StreamVarInteger(VIFS *stream, uint32_t data, uint32_t length)
References VarIntFileStream::bit_ptr, VarIntFileStream::buffer, BUFFER_LENGTH, BUFFER_REG_SIZE, VarIntFileStream::byte_ptr, F_WRITE, VarIntFileStream::fs, L_SHIFT.
Referenced by EncodeBody.
void CloseVarIntegerStream(VIFS *stream)
References F_CLOSE, VarIntFileStream::fs.
Referenced by EncodeBody.