varIntFile_IO.c
char* file_modes_arguments[][]
void _VUF_Clean(VUF *stream, char full)
References BUFFER_LENGTH, VarUnsignedIntFile::rw_buffer.
Referenced by VUF_append, VUF_initialize.
int VUF_initialize(VUF *stream, const char *file_name, file_modes io_mode)
References _VUF_Clean, VarUnsignedIntFile::bit_index, BUFFER_LENGTH, BUFFER_SIZE, VarUnsignedIntFile::byte_index, F_OPEN, F_READ, FILE_ACCESS_ERROR, VarUnsignedIntFile::fs, VarUnsignedIntFile::io_mode, Log_error, READ_BINARY, RES_OK, VarUnsignedIntFile::rw_buffer, WRITE_BINARY.
Referenced by Decoder_DecodeBody, testVUF_Read, testVUF_Write.
int VUF_append(VUF *stream, uint32_t data, uint32_t length)
References _VUF_Clean, VarUnsignedIntFile::bit_index, BUFFER_LENGTH, BUFFER_SIZE, VarUnsignedIntFile::byte_index, F_WRITE, VarUnsignedIntFile::fs, L_SHIFT, RES_OK, VarUnsignedIntFile::rw_buffer.
Referenced by testVUF_Write.
uint32_t VUF_read_stack(VUF *stream, uint32_t length)
References VarUnsignedIntFile::bit_index, BUFFER_LENGTH, BUFFER_SIZE, VarUnsignedIntFile::byte_index, F_READ, VarUnsignedIntFile::fs, VarUnsignedIntFile::rw_buffer.
Referenced by Decoder_DecodeBody, testVUF_Read.
int VUF_close(VUF *stream)
References VarUnsignedIntFile::bit_index, VarUnsignedIntFile::byte_index, F_CLOSE, VarUnsignedIntFile::fs, RES_OK.
Referenced by Decoder_DecodeBody, testVUF_Read, testVUF_Write.