local_differences.h
Ps
local_differences.h @Kevin-Caldwell @BrianShTsoi Central and Directional Local Difference Functions and Definitions
DLD
DLD_N
DLD_W
DLD_NW
DIRECTION
int32_t CentralLocalDifference(image *hIMG, INDEX z, INDEX y, INDEX x)
References LS, SR.
Referenced by LocalDirectionVector, UpdateWeights.
int32_t DirectionalLocalDifference(image *hIMG, INDEX z, INDEX y, INDEX x, int direction)
References LS, N, NW, SR, W.
int LocalDirectionVector(image *hIMG, int32_t **local_direction_vector, INDEX z, INDEX y, INDEX x)
References C, CentralLocalDifference, DLD, Hash_GetValue, InitVector, N, NW, predictor_constants, Ps.
Referenced by PredictedCentralLocalDifference.
int64_t PredictedCentralLocalDifference(image *hIMG, INDEX z, INDEX y, INDEX x)
References C, global_cache, InnerProduct, LocalDirectionVector, PredictorCache::weights.
Referenced by Predict, ReconstructPixel.