uhi_io.h
UHI_CACHE_LENGTH
uhi_io.h @Kevin-Caldwell @lalalalinn Functions for Uncompressed Hyperspectral Image files. The file consists of 14-bit pixel data stored as 16-bit data, prioritizing fast read and write capabilities. The First 3 16-bit values store the dimensions of the image, with the format: (Nx, Ny, Nz)
typedef struct UncompressedHyperspectralImage F_UHI
Stores UHI file streams. File format designed to store 16 bit pixel data for Hyperspectral Images. The first 3 data values represent the size of the hyperspectral image, and are followed by the pixel values. Designed to be a more RAM-friendly alternative to the image struct defined in image.h. The data is accessed from the filesystem instead of RAM, which increases latency and runtime, but reduces the RAM footprint of the overall program. fs: file_t object for handling file IO size: stores the dimensions of the Hyperspectral image cache: Unused 32 bit static array
typedef struct UncompressedHyperspectralImage UHI
typedef struct UncompressedHyperspectralImage uIMG
int UHI_Initialize(UHI *stream, dim3 buffer_size, const char *file_name, FileMode file_mode)
References UncompressedHyperspectralImage::cache, F_OPEN, UncompressedHyperspectralImage::fs, READ.
Referenced by test_UHI.
int UHI_WritePixel(const UHI *stream, dim3 index, PIXEL value)
Referenced by Proxy_SetPixel, test_UHI.
PIXEL UHI_ReadPixel(UHI *stream, dim3 index)
References UncompressedHyperspectralImage::cache, F_READ, F_SEEK, UncompressedHyperspectralImage::fs, UncompressedHyperspectralImage::size, dim3::x, dim3::y, dim3::z.
Referenced by Proxy_GetPixel, test_UHI.
PIXEL Proxy_GetPixel(uIMG *hIMG, INDEX x, INDEX y, INDEX z)
References UHI_ReadPixel.
void Proxy_SetPixel(uIMG *hIMG, INDEX x, INDEX y, INDEX z, PIXEL value)
References UHI_WritePixel.