csv-io.c
void SaveArrayAsCSV(uint16_t *data, UINT count, char *file_name)
csv-io.h @Kevin-Caldwell and @BrianShTsoi Functions for image file read and write to CSV
References F_CLOSE, F_OPEN, fp, Log_error, WRITE.
int SaveImageAsCSV(image *hIMG, char *file_name)
References F_CLOSE, F_OPEN, FILE_ACCESS_ERROR, fp, GetPixel, Log_error, RES_OK, image::size, WRITE, dim3::x, dim3::y, dim3::z.
Referenced by GeneratePerlinImage, GenerateVoronoiImage, PredictImage, TestReadImage.
int ReadImageFromCSV(image *hIMG, char *file_name)
References F_OPEN, F_READ, FILE_ACCESS_ERROR, fp, InitImage, Log_error, READ, RES_OK, dim3::x, dim3::y, dim3::z.
Referenced by EncodeImage, PredictImage, TestReadImage, TestReconstructor.