reconstructor.c
image* sample
Referenced by Decoder_DecodeBody, TestReconstructor.
void Reconstructor(image *predicted_values, image *reconstructed, FILE *file_ptr)
References C, InitalizeImageConstants, InitalizePredictorConstants, LoadConstantFile, NULL, Nz, PREDICTION_MODE, predictor_constants, PREDICTOR_CONSTANTS_LOCATION, Ps, ReconstructPixel, image::size, dim3::x, dim3::y, dim3::z.
Referenced by TestReconstructor.
void ReconstructPixel(image *mapped, image *data, INDEX z, INDEX y, INDEX x, FILE *file_ptr)
References C, ClippedQuantizerBinCenter, DoubleResolutionPredictedSample, DoubleResolutionPredictionError, F_WRITE, FindLocalSum, GetPixel, global_cache, HighResolutionPredictedSample, InitializeWeights, PredictedCentralLocalDifference, PredictedSample, QuantizerIndexUnmapper, SetPixel, UpdateWeights, PredictorCache::weights.
Referenced by Reconstructor.
void TestReconstructor(char *file_name)
References image::data, F_CLOSE, F_OPEN, global_cache, Image_Equals, InitializePredictorCache, InitImage, ReadImageFromCSV, Reconstructor, RunPredictor, sample, image::size, WRITE, dim3::x, dim3::y, dim3::z.
Referenced by main.