predictor.c
file_t* fp
Referenced by LoadConstantFile, Predict, ReadImageFromCSV, RunPredictor, SaveArrayAsCSV, SaveImageAsCSV.
int C
Referenced by InitializeWeights, LocalDirectionVector, Predict, PredictedCentralLocalDifference, Reconstructor, ReconstructPixel, RunPredictor, UpdateWeights.
void Predict(image *hIMG, image *result, INDEX z, INDEX y, INDEX x)
References C, ClippedQuantizerBinCenter, DEBUG, DoubleResolutionPredictedSample, DoubleResolutionPredictionError, F_WRITE, FindLocalSum, fp, GetPixel, global_cache, HighResolutionPredictedSample, InitializeWeights, MappedQuantizerIndex, PredictedCentralLocalDifference, PredictedSample, QuantizerIndex, SetPixel, UpdateWeights, PredictorCache::weights.
Referenced by RunPredictor.
int RunPredictor(image *hIMG, image *result)
References C, F_CLOSE, F_OPEN, FILE_READ_ERROR, fp, InitalizeImageConstants, InitalizePredictorConstants, LoadConstantFile, Log_add, Log_error, Nz, Predict, PREDICTION_MODE, predictor_constants, PREDICTOR_CONSTANTS_LOCATION, Ps, RES_OK, image::size, WRITE, dim3::x, dim3::y, dim3::z.
Referenced by PredictImage, TestReconstructor.