quantizer.c
uint16_t ClippedQuantizerBinCenter(uint16_t sample_value)
Referenced by Predict, ReconstructPixel.
int16_t PredictionResidual(uint16_t sample_value, uint16_t predicted_sample)
Referenced by QuantizerIndex.
int32_t QuantizerIndex(uint16_t sample_value, uint16_t predicted_sample)
quantizer.h @Kevin-Caldwell Functions For Quantizer
References PredictionResidual.
Referenced by Predict.
uint16_t minTheta(uint32_t predicted_sample)
References kSmax, kSmin, MIN.
Referenced by MappedQuantizerIndex, QuantizerIndexUnmapper.
int32_t QuantizerIndexUnmapper(uint16_t mapped_delta, uint16_t predicted_sample, int32_t drps)
References kSmin, minTheta.
Referenced by ReconstructPixel.
data_t MappedQuantizerIndex(int32_t quantizer_index, int32_t predicted_sample, uint32_t double_res_predicted_sample)
References minTheta.
Referenced by Predict.