compression
int D
int S_MIN
int S_MAX
int S_MID
int P
int W_RES
W_MIN
int W_MAX
int R
int M
int V_MIN
int V_MAX
int T_INC
int U_MAX
int GAMMA_0
int K
int GAMMA_STAR
int K_ZPRIME
Ps(z)
local_sum(x, y, z, data)
Referenced by local_diff_vector, prediction.
local_diff_vector(x, y, z, data)
References local_sum, Ps.
Referenced by predictor, predictor_debug, unpredictor.
init_weight_vector(z)
References Ps.
Referenced by predictor, predictor_debug, unpredictor.
prediction(ld_vector, weight_vector, x, y, z, data)
References local_sum.
Referenced by predictor, predictor_debug, unpredictor.
updated_weight_vector(s_tilde, weight_vector, ld_vector, x, y, z, data)
References helperlib.sign.
Referenced by predictor, predictor_debug, unpredictor.
mapper(delta, s_hat, s_tilde)
Referenced by predictor, predictor_debug.
predictor(data)
References init_weight_vector, local_diff_vector, mapper, prediction, updated_weight_vector.
predictor_debug(data)
References init_weight_vector, local_diff_vector, mapper, prediction, updated_weight_vector.
GPO2(k, j)
References helperlib.dec_to_bin.
Referenced by encoder.
encoder(mapped_delta)
References helperlib.dec_to_bin, GPO2.
increment_xyz(x, y, z, Nx, Ny, Nz)
Referenced by decoder.
inv_GPO2(k, encoded, i)
References helperlib.bin_to_dec.
Referenced by decoder.
decoder(encoded, Nx, Ny, Nz)
References helperlib.bin_to_dec, increment_xyz, inv_GPO2.
unmapper(mapped_delta, s_hat, s_tilde)
Referenced by unpredictor.
np.array unpredictor(np.array mapped, int Nx, int Ny, int Nz)
References init_weight_vector, local_diff_vector, prediction, unmapper, updated_weight_vector.