image.h
FRAME_SIZE
image.h @Kevin-Caldwell Image Structure for Storing 3D bitmaps with a maximum dynamic range of 16 bits Features Initialize Image Get/Set Pixels Image Compare Coordinate Transform from x,y,z to t,z Uses Raw Data Predicted Image Dependencies math_functions.h constants.h stdlib.h
MAP3_1
GetT
GetX
GetY
S
typedef struct image image
Image Stuct for storing all the contexts of a hyperspectral image in a linear array. The size member is a dim3 which contains the dimensions of the image in the format: {Nx, Ny, Nz} The data member is a dynamically allocated array of PIXELs arranged according to the MAP3_1 Macro defined in image.h It has only been created as a testing feature. The entire hyperspectral image cannot be stored in RAM on an embedded device such as the STM32H7. The UHI file structure replaces this struct when the MEMORY_SAVING feature is enabled through CMake.
typedef struct image image3
typedef struct image2 image2
Unused Struct for 2-D images.
int InitImage(image *img_p, size_t x, size_t y, size_t z)
References image::data, image::size, dim3::x, dim3::y, dim3::z.
Referenced by GeneratePerlinImage, GenerateVoronoiImage, InitializePredictorCache, PredictImage, ReadImageFromCSV, test_UHI, TestReconstructor.
PIXEL GetPixel(image *hIMG, INDEX x, INDEX y, INDEX z)
References image::data, MAP3_1, image::size.
Referenced by EncodeBody, Predict, ReconstructPixel, SaveImageAsCSV, test_UHI.
PIXEL * GetFrame(image *hIMG, INDEX y)
References image::data, FRAME_SIZE, image::size.
void SetPixel(image *hIMG, INDEX x, INDEX y, INDEX z, PIXEL data)
References image::data, MAP3_1, image::size.
Referenced by Decoder_DecodeBody, GenerateVoronoiFlat3DLocal, GenerateVoronoiFlat3DNaive, Perlin4, Predict, ReconstructPixel, ShadeVoronoiBox3.
int Image_Equals(image *img1, image *img2)
References image::data, image::size, dim3::x, dim3::y, dim3::z.
Referenced by TestReconstructor.