perlin_noise.c
typedef struct fVector3 fVector3
3D floating point vector
float dot(fVector3 u, fVector3 v)
References fVector3::x, fVector3::y, fVector3::z.
Referenced by normalize, SolvePerlin4.
fVector3 normalize(fVector3 v)
References dot.
Referenced by SolvePerlin4.
float interpolate(float a0, float a1, float w)
uint16_t mapper(float val)
Referenced by SolvePerlin4.
fVector3 RandomizeVector(int vector_x, int vector_y, int vector_z)
References SQ.
Referenced by SolvePerlin4.
uint16_t SolvePerlin4(int x, int y, int z, int len, dim3 size)
References dot, mapper, normalize, RandomizeVector.
Referenced by Perlin4.
void Perlin4(image *result, int cube_side)
References NULL, SetPixel, image::size, SolvePerlin4, dim3::x, dim3::y, dim3::z.
Referenced by GeneratePerlinImage.
void GeneratePerlinImage(dim3 size, int index, int length)
References image::data, InitImage, Perlin4, SaveImageAsCSV, dim3::x, dim3::y, dim3::z.
Referenced by main.