test_varInt.c
void printBits(size_t const size, void const *const ptr)
Referenced by print_buffer.
void print_buffer(VUF *f)
References VarUnsignedIntFile::bit_index, BUFFER_LENGTH, VarUnsignedIntFile::byte_index, printBits, VarUnsignedIntFile::rw_buffer.
Referenced by testVUF_Read, testVUF_Write.
int testVUF_Write()
References Log_add, print_buffer, VUF_append, VUF_close, VUF_initialize, WRITE_BINARY.
int testVUF_Read()
References print_buffer, READ_BINARY, VUF_close, VUF_initialize, VUF_read_stack.