header.h
void PrepareImageMetadata(uint8_t *essential)
header.h Kevin Caldwell File Contains Functions for Preparing Image, Predictor, Encoder and Entropy coder Header Sections of the Compressed Image.
References B, D, Encode, ENTROPY_CODER, kUnsignedSamples, Nx, Ny, Nz, PrintBinary, QUANTIZER_FIDELITY_CONTROL, SIZEOF_HEADER_ESSENTIAL, TABLE_COUNT.
Referenced by TestHeader.
void PreparePredictorMetadata(uint8_t *predicted_metadata)
References BAND_VARYING_DAMPING_FLAG, BAND_VARYING_OFFSET_FLAG, DAMPING_TABLE_FLAG, Encode, FIXED_DAMPING, FIXED_OFFSET, Hash_GetValue, kP, kR, kVMax, kVMin, LOCAL_SUM_TYPE, OFFSET_TABLE_FLAG, Omega, PREDICTION_MODE, predictor_constants, RESOLUTION, SAMPLE_REP_FLAG, WEIGHT_EXPONENT_OFFSET_FLAG, WEIGHT_INITIALIZATION, WEIGHT_INITIALIZATION_TABLE_FLAG, WEO_TABLE_FLAG.
Referenced by TestHeader.
void PrepareSampleAdaptiveEntropyCoder(uint8_t *entropy_coder_metadata)
References ACCUMULATOR_INITIALIZATION, ACCUMULATOR_INITIALIZATION_TABLE_FLAG, Encode, INITIAL_COUNT_EXPONENT, RESCALING_COUNTER_SIZE, UNARY_LENGTH_LIMIT.
Referenced by TestHeader.