helperlib
sign(x)
Referenced by compression.updated_weight_vector.
dec_to_bin(d, width)
Referenced by compression.encoder, compression.GPO2.
bin_to_dec(b)
Referenced by compression.decoder, compression.inv_GPO2.