math_functions.c
UINT Euclidian2(dim2 pt1, dim2 pt2)
References SQ, dim2::x, dim2::y.
UINT Euclidian3(dim3 pt1, dim3 pt2)
References SQ, dim3::x, dim3::y, dim3::z.
UINT Manhattan2(dim2 pt1, dim2 pt2)
References dim2::x, dim2::y.
Referenced by GenerateVoronoiFlat2D.
UINT Manhattan3(dim3 pt1, dim3 pt2)
References dim3::x, dim3::y, dim3::z.
Referenced by GeneratePointLocales, GetMinDistance3Locales, GetMinDistance3Naive.