weights.h
Ps
weights.h @Kevin-Caldwell Functions for Initializing, Calculating and Updating Weights for Predictor and Reconstructor.
int InitializeWeights(int32_t **weight_ptr, INDEX z, INDEX y, INDEX x)
References BPOW, C, InitVector, Omega, PREDICTION_MODE, RES_OK.
Referenced by InitializePredictorCache, Predict, ReconstructPixel.
int32_t DoubleResolutionPredictionError(int16_t clipped_quantizer_bin_center, int32_t double_resolution_predicted_sample)
Referenced by Predict, ReconstructPixel.
int32_t WeightUpdateScalingExponent(INDEX y, INDEX x)
References CLIP, D, kTInc, kVMax, kVMin, Nx, Omega.
Referenced by UpdateWeights.
int UpdateWeights(image *hIMG, int32_t *weights, INDEX z, INDEX y, INDEX x, int32_t double_resolution_prediction_error)
References C, CentralLocalDifference, CLIP, DLD, kOmegaMax, kOmegaMin, SIGN_P, WeightUpdateScalingExponent.
Referenced by Predict, ReconstructPixel.