load_constants.c
int LoadConstantFile(const char *file_name, HashTable *result)
load_constants.h @Kevin-Caldwell Abstractions for Loading .CONST files Features Custom .CONST file format with easy-to-read Constant Parameter Storage Uses Interpreting .CONST Files to load constants for all modules Stores result in a HashTable structure Dependencies hash_table.h Internal Dependencies stdio.h TODO Add a SaveConstantFile Function FUNCDEF: int SaveConstantFile(const char* file_name, HashTable* save_input)
References F_CLOSE, F_OPEN, fp, Hash_AddEntry, KEY_LENGTH, NULL, READ.
Referenced by EncodeImage, Reconstructor, RunPredictor.