hash_table.h
HASH_CAPACITY
hash_table.h @Kevin-Caldwell Hash Table Implementation for Storing Constants. Uses Dynamically allocated memory for storage Dependencies stdlib inttypes string Features Initialization Deletion Add Entries Get Index Get and Set Value TODO Comments Statically Allocated Memory (High Priority)
KEY_LENGTH
typedef struct HashTable HashTable
int Hash_InitializeHashTable(HashTable **hash)
int Hash_DeleteHashTable(HashTable *hash)
int Hash_AddEntry(HashTable *hash, const char *name, int32_t data)
References HashTable::data, HASH_CAPACITY, KEY_LENGTH, HashTable::keys, HashTable::len.
Referenced by LoadConstantFile.
int Hash_GetIndex(HashTable *hash, const char *key)
References KEY_LENGTH, HashTable::keys, HashTable::len.
Referenced by Hash_GetValue, Hash_SetValue.
int32_t Hash_GetValue(HashTable *hash, const char *key)
References HashTable::data, Hash_GetIndex.
Referenced by LocalDirectionVector, PreparePredictorMetadata.
int Hash_SetValue(HashTable *hash, const char *key, int32_t new_data)
References HashTable::data, Hash_GetIndex.